spring:
  datasource:
    customer-db:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://192.168.0.110:3306/Customer_DB?useAffectedRows=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
      username: tomcat
      password: 80201288@qq.com
    wechat-db:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://192.168.0.110:3306/Wx_DB?useAffectedRows=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
      username: tomcat
      password: 80201288@qq.com
  data:
    mongodb:
      uri: mongodb://tomcat:80201288@127.0.0.1:27077/
      authentication-database: admin
      database: test_db
eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.110:8761/eureka
  instance:
    prefer-ip-address: true
    ip-address: 19.168.0.106
server:
  port: 8080
token:
  cookie:
    name: sdcsoft.ucookie
    domain: kuaixin.picp.net
    path: /
fileupload:
  boiler:
    path: E:/Projects/Github/Java/SdcSoft.com.cn/aupload/boiler/
    return-image-prefix: /boiler
logging:
  level:
    cn:
      com:
        sdcsoft:
          webapi:
            web:
              boilermanage:
                mapper: DEBUG