spring:
  datasource:
    boilermanage:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://192.168.0.110:3306/Customer_DB?useAffectedRows=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
      username: root
      password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.110:8761/eureka
  instance:
    prefer-ip-address: true
    ip-address: 192.168.0.156
server:
  port: 8080
token:
  cookie:
    name: sdcsoft.ucookie
    domain:  sdcsoft.com.cn
    path: /