spring:
  datasource:
    enterprise-db:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://172.17.201.251:3306/test_sdcsoft_db?useAffectedRows=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
      username: dba_user
      password: Test@163.com
    customer-db:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://172.17.201.251:3306/Customer_DB?useAffectedRows=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
      username: dba_user
      password: Test@163.com
    wechat-db:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://172.17.201.251:3306/Wechat_DB?useAffectedRows=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
      username: dba_user
      password: Test@163.com
  data:
    mongodb:
      uri: mongodb://tomcat:80201288@172.17.201.251:27017/
      authentication-database: admin
      database: test_db
  rabbitmq:
    base:
      host: 192.168.0.110
      port: 5672
      username: tomcat
      password: 80201288
      virtual-host: MsgCenter
eureka:
  client:
    service-url:
      defaultZone: http://172.17.30.183:8761/eureka
  instance:
    prefer-ip-address: true
    ip-address: 172.17.30.183
cloud:
  lan-api: LAN-API2
server:
  port: 8080
token:
  cookie:
    name: sdcsoft.ucookie
    domain:  sdcsoft.com.cn
    path: /
fileupload:
  return-image-prefix: /files #nginx中访问文件的路径
  enterprise:
    path: /enterprise
  boiler:
    path: /boiler #docker容器中文件上传目录
  enduser:
    path: /enduser #docker容器中文件上传目录
