spring:
  application:
    name: wxmanage
  profiles:
    active: dev
  cache:
    type: ehcache
    ehcache:
      config: classpath:ehcache.xml
  rabbitmq:
    host: 47.94.5.49
    port: 5672
    username: tomcat
    password: 80201288
    virtual-host: MsgCenter
    template:
      exchange: WechatDeviceExMapMobileExchange
wechat:
  wx-openid: https://api.weixin.qq.com
device:
  cache: http://47.94.5.49:8080/device/get
  command: http://commands.sdcsoft.com.cn
sms:
  interval: 5
