spring:
  application:
    name: wxmanage
  profiles:
    active: dev
wechat:
  wx-openid: https://api.weixin.qq.com
device:
  cache: http://output.sdcsoft.com.cn
  command: http://commands.sdcsoft.com.cn
