spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  application:
    name: wxmanage
  profiles:
    active: dev
  cache:
    type: ehcache
    ehcache:
      config: classpath:ehcache.xml
wechat:
  wx-openid: https://api.weixin.qq.com
device:
  cache:
    url: http://47.94.5.49:8080
    data: ${device.cache.url}/device/get
    online: ${device.cache.url}/device/online
  command: http://commands.sdcsoft.com.cn
sms:
  interval: 5
#reload:
#  queue: DeviceInputCacheReloadQueue
