spring:
  datasource:
    customer-db:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://47.94.5.49:3306/Customer_DB?useAffectedRows=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
      username: dba_user
      password: Test@163.com
    enduser-db:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://47.94.5.49:3306/EndUser_DB?useAffectedRows=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
      username: dba_user
      password: Test@163.com
    wechat-db:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://47.94.5.49:3306/Wechat_DB?useAffectedRows=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
      username: dba_user
      password: Test@163.com
  data:
    mongodb:
      uri: mongodb://tomcat:80201288@127.0.0.1:27077
      authentication-database: admin
      database: test_db
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  instance:
    prefer-ip-address: true
    ip-address: 192.168.0.108
server:
  port: 8080
token:
  cookie:
    name: sdcsoft.ucookie
    domain:
    path: /
fileupload:
  return-image-prefix: /boiler
  boiler:
    path: E:/Projects/Github/Java/SdcSoft.com.cn/aupload/boiler/
  enduser:
    path: E:/Projects/Github/Java/SdcSoft.com.cn/aupload/enduser #docker容器中文件上传目录
logging:
  level:
    cn:
      com:
        sdcsoft:
          webapi:
            web:
              boilermanage:
                mapper: DEBUG