spring:
  application:
    name: wxmanage
  profiles:
    active: dev
  cache:
    type: ehcache
    ehcache:
      config: classpath:ehcache.xml
wechat:
  wx-openid: https://api.weixin.qq.com
device:
  cache: http://47.94.5.49:8080/device/get
  command: http://commands.sdcsoft.com.cn
