spring:
  application:
    name: wxmanage
  profiles:
    active: dev
wechat:
  wx-openid: https://api.weixin.qq.com
device:
  cache: http://172.17.201.251:8080/device/get
  command: http://commands.sdcsoft.com.cn
